import sqlite3

connection = sqlite3.connect("database.db")

cursor = connection.cursor()

cursor.execute("CREATE TABLE supplier (name TEXT PRIMARY KEY)")
cursor.execute("CREATE TABLE category (name TEXT PRIMARY KEY)")
cursor.execute("""
	CREATE TABLE product (id INTEGER PRIMARY KEY,
	name TEXT,
	price REAL,
	category TEXT NOT NULL, 
	supplier TEXT NOT NULL,
	FOREIGN KEY (category) REFERENCES category (name),
	FOREIGN KEY (supplier) REFERENCES supplier (name))
	""")
	
cursor.execute("""INSERT INTO supplier (name) VALUES
	('Aldi Süd'),
	('Aldi Nord'),
	('Lidl'),
	('Rewe'),
	('Edeka'),
	('Penny'),
	('Netto')
	""")
	
cursor.execute("""INSERT INTO category (name) VALUES
	('Brot & Brötchen'),
	('Brioche'),
	('Käse'),
	('Kaffee'),
	('Tee'),
	('Nudeln & Reis')
	""")

cursor.execute("""INSERT INTO product (id, name, price, category, supplier) VALUES
       (1, 'Kräuter-Baguette', 0.28, 'Brot & Brötchen', 'Aldi Süd'),
       (2, 'Kräuter-Baguette', 0.28, 'Brot & Brötchen', 'Aldi Nord'),
       (3, 'Kräuter-Baguette', 0.34, 'Brot & Brötchen', 'Lidl'),
       (4, 'Kräuter-Baguette', 0.34, 'Brot & Brötchen', 'Rewe'),
       (5, 'Kräuter-Baguette', 0.34, 'Brot & Brötchen', 'Edeka'),
       (6, 'Milchbrötchen', 0.27, 'Brot & Brötchen', 'Aldi Süd'),
       (7, 'Milchbrötchen', 0.27, 'Brot & Brötchen', 'Aldi Nord'),
       (8, 'Milchbrötchen', 0.27, 'Brot & Brötchen', 'Lidl'),
       (9, 'Milchbrötchen', 0.27, 'Brot & Brötchen', 'Rewe'),
       (10, 'Milchbrötchen', 0.27, 'Brot & Brötchen', 'Edeka'),
       (11, 'Milchbrötchen', 0.31, 'Brot & Brötchen', 'Penny'),
       (12, 'Milchbrötchen', 0.27, 'Brot & Brötchen', 'Netto'),
       (13, 'Roggenmischbrot', NULL, 'Brot & Brötchen', 'Edeka'),
       (14, 'Roggenmischbrot', 0.18, 'Brot & Brötchen', 'Netto'),
       (15, 'Croissants', 0.62, 'Brot & Brötchen', 'Aldi Süd'),
       (16, 'Croissants', 0.68, 'Brot & Brötchen', 'Aldi Nord'),
       (17, 'Croissants', 0.62, 'Brot & Brötchen', 'Lidl'),
       (18, 'Croissants', 0.70, 'Brot & Brötchen', 'Rewe'),
       (19, 'Croissants', 0.62, 'Brot & Brötchen', 'Edeka'),
       (20, 'Croissants', 0.62, 'Brot & Brötchen', 'Penny'),
       (21, 'Croissants', 0.65, 'Brot & Brötchen', 'Netto'),
       (22, 'Dreikorntoast', 0.11, 'Brot & Brötchen', 'Aldi Süd'),
       (23, 'Dreikorntoast', 0.11, 'Brot & Brötchen', 'Aldi Nord'),
       (24, 'Dreikorntoast', 0.14, 'Brot & Brötchen', 'Lidl'),
       (25, 'Dreikorntoast', 0.14, 'Brot & Brötchen', 'Rewe'),
       (26, 'Dreikorntoast', 0.14, 'Brot & Brötchen', 'Edeka'),
       (27, 'Dreikorntoast', 0.12, 'Brot & Brötchen', 'Penny'),
       (28, 'Dreikorntoast', 0.12, 'Brot & Brötchen', 'Netto'),
       (29, 'Toastbrötchen', NULL, 'Brot & Brötchen', 'Aldi Nord'),
       (30, 'Toastbrötchen', 0.30, 'Brot & Brötchen', 'Edeka'),
       (31, 'Toastbrötchen', 0.36, 'Brot & Brötchen', 'Penny'),
       (32, 'Toastbrötchen', 0.27, 'Brot & Brötchen', 'Netto'),
       (33, 'Sandwich-Toast', 0.20, 'Brot & Brötchen', 'Aldi Süd'),
       (34, 'Sandwich-Toast', 0.11, 'Brot & Brötchen', 'Aldi Nord'),
       (35, 'Sandwich-Toast', 0.13, 'Brot & Brötchen', 'Lidl'),
       (36, 'Sandwich-Toast', 0.13, 'Brot & Brötchen', 'Rewe'),
       (37, 'Sandwich-Toast', 0.11, 'Brot & Brötchen', 'Edeka'),
       (38, 'Sandwich-Toast', 0.13, 'Brot & Brötchen', 'Penny'),
       (39, 'Sandwich-Toast', 0.13, 'Brot & Brötchen', 'Netto'),
       (40, 'Knäckebrot', 0.52, 'Brot & Brötchen', 'Aldi Süd'),
       (41, 'Knäckebrot', 0.24, 'Brot & Brötchen', 'Aldi Nord'),
       (42, 'Knäckebrot', 0.28, 'Brot & Brötchen', 'Lidl'),
       (43, 'Knäckebrot', NULL, 'Brot & Brötchen', 'Edeka'),
       (44, 'Knäckebrot', 0.24, 'Brot & Brötchen', 'Penny'),
       (45, 'Knäckebrot', 0.24, 'Brot & Brötchen', 'Netto'),
       (46, 'Buttertoast', 0.24, 'Brot & Brötchen', 'Aldi Süd'),
       (47, 'Buttertoast', 0.12, 'Brot & Brötchen', 'Aldi Nord'),
       (48, 'Buttertoast', 0.16, 'Brot & Brötchen', 'Lidl'),
       (49, 'Buttertoast', 0.16, 'Brot & Brötchen', 'Rewe'),
       (50, 'Buttertoast', 0.14, 'Brot & Brötchen', 'Edeka'),
       (51, 'Buttertoast', 0.14, 'Brot & Brötchen', 'Penny'),
       (52, 'Buttertoast', 0.14, 'Brot & Brötchen', 'Netto'),
       (53, 'Rosinenschnitten', 0.35, 'Brot & Brötchen', 'Aldi Süd'),
       (54, 'Rosinenschnitten', 0.25, 'Brot & Brötchen', 'Aldi Nord'),
       (55, 'Rosinenschnitten', NULL, 'Brot & Brötchen', 'Lidl'),
       (56, 'Rosinenschnitten', NULL, 'Brot & Brötchen', 'Edeka'),
       (57, 'Rosinenschnitten', 0.25, 'Brot & Brötchen', 'Penny'),
       (58, 'Rosinenschnitten', NULL, 'Brot & Brötchen', 'Netto'),
       (59, 'Ciabatta', 1.31, 'Brot & Brötchen', 'Aldi Süd'),
       (60, 'Ciabatta', 1.31, 'Brot & Brötchen', 'Aldi Nord'),
       (61, 'Ciabatta', 1.31, 'Brot & Brötchen', 'Lidl'),
       (62, 'Ciabatta', 1.31, 'Brot & Brötchen', 'Rewe'),
       (63, 'Ciabatta', NULL, 'Brot & Brötchen', 'Penny'),
       (64, 'Ciabatta', NULL, 'Brot & Brötchen', 'Netto'),
       (65, 'Baguette', 0.27, 'Brot & Brötchen', 'Aldi Süd'),
       (66, 'Baguette', 0.27, 'Brot & Brötchen', 'Aldi Nord'),
       (67, 'Baguette', 0.27, 'Brot & Brötchen', 'Lidl'),
       (68, 'Baguette', 0.27, 'Brot & Brötchen', 'Rewe'),
       (69, 'Baguette', NULL, 'Brot & Brötchen', 'Edeka'),
       (70, 'Baguette', NULL, 'Brot & Brötchen', 'Netto'),
       (71, 'Finn-Brötchen', 0.38, 'Brot & Brötchen', 'Aldi Süd'),
       (72, 'Finn-Brötchen', 0.38, 'Brot & Brötchen', 'Aldi Nord'),
       (73, 'Finn-Brötchen', NULL, 'Brot & Brötchen', 'Lidl'),
       (74, 'Finn-Brötchen', 0.38, 'Brot & Brötchen', 'Edeka'),
       (75, 'Finn-Brötchen', 0.38, 'Brot & Brötchen', 'Penny'),
       (76, 'Finn-Brötchen', 0.34, 'Brot & Brötchen', 'Netto'),
       (77, 'Schokobrötchen', 0.41, 'Brot & Brötchen', 'Aldi Süd'),
       (78, 'Schokobrötchen', 0.41, 'Brot & Brötchen', 'Aldi Nord'),
       (79, 'Schokobrötchen', 0.41, 'Brot & Brötchen', 'Lidl'),
       (80, 'Schokobrötchen', 0.41, 'Brot & Brötchen', 'Rewe'),
       (81, 'Schokobrötchen', 0.41, 'Brot & Brötchen', 'Edeka'),
       (82, 'Schokobrötchen', 0.41, 'Brot & Brötchen', 'Penny'),
       (83, 'Schokobrötchen', 0.41, 'Brot & Brötchen', 'Netto'),
       (84, 'Toast, Vollkorn', NULL, 'Brot & Brötchen', 'Aldi Nord'),
       (85, 'Toast, Vollkorn', 0.12, 'Brot & Brötchen', 'Lidl'),
       (86, 'Toast, Vollkorn', 0.12, 'Brot & Brötchen', 'Rewe'),
       (87, 'Toast, Vollkorn', 0.14, 'Brot & Brötchen', 'Edeka'),
       (88, 'Toast, Vollkorn', 0.14, 'Brot & Brötchen', 'Penny'),
       (89, 'Toast, Vollkorn', NULL, 'Brot & Brötchen', 'Netto'),
       (90, 'Baguette Brötchen', 0.23, 'Brot & Brötchen', 'Aldi Süd'),
       (91, 'Baguette Brötchen', 0.13, 'Brot & Brötchen', 'Aldi Nord'),
       (92, 'Baguette Brötchen', 0.15, 'Brot & Brötchen', 'Lidl'),
       (93, 'Baguette Brötchen', 0.15, 'Brot & Brötchen', 'Rewe'),
       (94, 'Baguette Brötchen', 0.13, 'Brot & Brötchen', 'Edeka'),
       (95, 'Baguette Brötchen', NULL, 'Brot & Brötchen', 'Penny'),
       (96, 'Baguette Brötchen', NULL, 'Brot & Brötchen', 'Netto'),
       (97, 'Hamburger Brötchen', 0.69, 'Brot & Brötchen', 'Aldi Süd'),
       (98, 'Hamburger Brötchen', 0.65, 'Brot & Brötchen', 'Aldi Nord'),
       (99, 'Hamburger Brötchen', 0.53, 'Brot & Brötchen', 'Lidl'),
       (100, 'Hamburger Brötchen', 0.53, 'Brot & Brötchen', 'Rewe'),
       (101, 'Hamburger Brötchen', 0.63, 'Brot & Brötchen', 'Edeka'),
       (102, 'Hamburger Brötchen', 0.53, 'Brot & Brötchen', 'Penny'),
       (103, 'Hamburger Brötchen', NULL, 'Brot & Brötchen', 'Netto'),
       (104, 'Brioche', NULL, 'Brot & Brötchen', 'Aldi Süd'),
       (105, 'Brioche', NULL, 'Brot & Brötchen', 'Aldi Nord'),
       (106, 'Brioche', NULL, 'Brot & Brötchen', 'Lidl'),
       (107, 'Brioche', NULL, 'Brot & Brötchen', 'Rewe'),
       (108, 'Brioche', NULL, 'Brot & Brötchen', 'Edeka'),
       (109, 'Brioche', NULL, 'Brot & Brötchen', 'Penny'),
       (110, 'Brioche', NULL, 'Brot & Brötchen', 'Netto'),
       (111, 'Bauernbrot', 0.20, 'Brot & Brötchen', 'Aldi Süd'),
       (112, 'Bauernbrot', 0.12, 'Brot & Brötchen', 'Aldi Nord'),
       (113, 'Bauernbrot', NULL, 'Brot & Brötchen', 'Lidl'),
       (114, 'Bauernbrot', 0.14, 'Brot & Brötchen', 'Rewe'),
       (115, 'Bauernbrot', 0.13, 'Brot & Brötchen', 'Edeka'),
       (116, 'Bauernbrot', NULL, 'Brot & Brötchen', 'Penny'),
       (117, 'Bauernbrot', 0.13, 'Brot & Brötchen', 'Netto'),
       (118, 'Fladenbrot', 0.20, 'Brot & Brötchen', 'Aldi Süd'),
       (119, 'Fladenbrot', 0.20, 'Brot & Brötchen', 'Aldi Nord'),
       (120, 'Fladenbrot', 0.20, 'Brot & Brötchen', 'Lidl'),
       (121, 'Fladenbrot', 0.20, 'Brot & Brötchen', 'Rewe'),
       (122, 'Fladenbrot', 0.20, 'Brot & Brötchen', 'Edeka'),
       (123, 'Fladenbrot', 0.20, 'Brot & Brötchen', 'Penny'),
       (124, 'Fladenbrot', 0.20, 'Brot & Brötchen', 'Netto'),
       (125, 'Krustenbrot', NULL, 'Brot & Brötchen', 'Aldi Süd'),
       (126, 'Krustenbrot', 0.12, 'Brot & Brötchen', 'Aldi Nord'),
       (127, 'Krustenbrot', 0.20, 'Brot & Brötchen', 'Lidl'),
       (128, 'Krustenbrot', 0.20, 'Brot & Brötchen', 'Rewe'),
       (129, 'Krustenbrot', 0.22, 'Brot & Brötchen', 'Edeka'),
       (130, 'Krustenbrot', 0.22, 'Brot & Brötchen', 'Penny'),
       (131, 'Krustenbrot', NULL, 'Brot & Brötchen', 'Netto'),
       (132, 'Käseaufschnitt', NULL, 'Käse', 'Aldi Süd'),
       (133, 'Käseaufschnitt', 1.56, 'Käse', 'Aldi Nord'),
       (134, 'Käseaufschnitt', 2.60, 'Käse', 'Lidl'),
       (135, 'Käseaufschnitt', 2.56, 'Käse', 'Rewe'),
       (136, 'Käseaufschnitt', 2.26, 'Käse', 'Edeka'),
       (137, 'Käseaufschnitt', NULL, 'Käse', 'Penny'),
       (138, 'Käseaufschnitt', NULL, 'Käse', 'Netto'),
       (139, 'Mozzarella', 0.79, 'Käse', 'Aldi Süd'),
       (140, 'Mozzarella', 0.52, 'Käse', 'Aldi Nord'),
       (141, 'Mozzarella', 0.30, 'Käse', 'Lidl'),
       (142, 'Mozzarella', 0.49, 'Käse', 'Rewe'),
       (143, 'Mozzarella', 0.52, 'Käse', 'Edeka'),
       (144, 'Mozzarella', 0.75, 'Käse', 'Penny'),
       (145, 'Mozzarella', 0.55, 'Käse', 'Netto'),
       (146, 'Gouda, in Scheiben', 1.00, 'Käse', 'Aldi Süd'),
       (147, 'Gouda, in Scheiben', 0.83, 'Käse', 'Aldi Nord'),
       (148, 'Gouda, in Scheiben', 0.90, 'Käse', 'Lidl'),
       (149, 'Gouda, in Scheiben', 1.16, 'Käse', 'Rewe'),
       (150, 'Gouda, in Scheiben', 1.75, 'Käse', 'Edeka'),
       (151, 'Gouda, in Scheiben', 1.62, 'Käse', 'Penny'),
       (152, 'Gouda, in Scheiben', NULL, 'Käse', 'Netto'),
       (153, 'Frischkäse, Doppelrahmstufe', NULL, 'Käse', 'Aldi Süd'),
       (154, 'Frischkäse, Doppelrahmstufe', NULL, 'Käse', 'Aldi Nord'),
       (155, 'Frischkäse, Doppelrahmstufe', NULL, 'Käse', 'Lidl'),
       (156, 'Frischkäse, Doppelrahmstufe', 0.76, 'Käse', 'Rewe'),
       (157, 'Frischkäse, Doppelrahmstufe', 0.80, 'Käse', 'Edeka'),
       (158, 'Frischkäse, Doppelrahmstufe', NULL, 'Käse', 'Penny'),
       (159, 'Frischkäse, Doppelrahmstufe', NULL, 'Käse', 'Netto'),
       (160, 'Österreichischer Bergkäse', 4.59, 'Käse', 'Aldi Süd'),
       (161, 'Österreichischer Bergkäse', 4.79, 'Käse', 'Aldi Nord'),
       (162, 'Österreichischer Bergkäse', NULL, 'Käse', 'Lidl'),
       (163, 'Österreichischer Bergkäse', NULL, 'Käse', 'Rewe'),
       (164, 'Österreichischer Bergkäse', NULL, 'Käse', 'Edeka'),
       (165, 'Österreichischer Bergkäse', NULL, 'Käse', 'Penny'),
       (166, 'Österreichischer Bergkäse', NULL, 'Käse', 'Netto'),
       (167, 'Feta', 1.00, 'Käse', 'Aldi Süd'),
       (168, 'Feta', 1.44, 'Käse', 'Aldi Nord'),
       (169, 'Feta', NULL, 'Käse', 'Lidl'),
       (170, 'Feta', 1.46, 'Käse', 'Rewe'),
       (171, 'Feta', 1.49, 'Käse', 'Edeka'),
       (172, 'Feta', NULL, 'Käse', 'Penny'),
       (173, 'Feta', NULL, 'Käse', 'Netto'),
       (174, 'Brie', 1.49, 'Käse', 'Aldi Nord'),
       (175, 'Brie', NULL, 'Käse', 'Lidl'),
       (176, 'Brie', 1.60, 'Käse', 'Rewe'),
       (177, 'Brie', NULL, 'Käse', 'Edeka'),
       (178, 'Brie', NULL, 'Käse', 'Penny'),
       (179, 'Brie', NULL, 'Käse', 'Netto'),
       (180, 'Harzer', 0.89, 'Käse', 'Aldi Süd'),
       (181, 'Harzer', 0.89, 'Käse', 'Aldi Nord'),
       (182, 'Harzer', NULL, 'Käse', 'Lidl'),
       (183, 'Harzer', 0.65, 'Käse', 'Rewe'),
       (184, 'Harzer', 0.75, 'Käse', 'Edeka'),
       (185, 'Harzer', 0.65, 'Käse', 'Penny'),
       (186, 'Harzer', NULL, 'Käse', 'Netto'),
       (187, 'Hüttenkäse', 0.89, 'Käse', 'Aldi Süd'),
       (188, 'Hüttenkäse', 0.84, 'Käse', 'Aldi Nord'),
       (189, 'Hüttenkäse', NULL, 'Käse', 'Lidl'),
       (190, 'Hüttenkäse', 0.74, 'Käse', 'Rewe'),
       (191, 'Hüttenkäse', 0.80, 'Käse', 'Edeka'),
       (192, 'Hüttenkäse', 0.84, 'Käse', 'Penny'),
       (193, 'Hüttenkäse', NULL, 'Käse', 'Netto'),
       (194, 'Camembert', NULL, 'Käse', 'Aldi Süd'),
       (195, 'Camembert', 1.55, 'Käse', 'Aldi Nord'),
       (196, 'Camembert', NULL, 'Käse', 'Lidl'),
       (197, 'Camembert', NULL, 'Käse', 'Rewe'),
       (198, 'Camembert', 1.55, 'Käse', 'Edeka'),
       (199, 'Camembert', NULL, 'Käse', 'Penny'),
       (200, 'Camembert', NULL, 'Käse', 'Netto'),
       (201, 'Schmelzkäsescheiben', 0.72, 'Käse', 'Aldi Süd'),
       (202, 'Schmelzkäsescheiben', 0.40, 'Käse', 'Aldi Nord'),
       (203, 'Schmelzkäsescheiben', 0.46, 'Käse', 'Lidl'),
       (204, 'Schmelzkäsescheiben', 0.40, 'Käse', 'Rewe'),
       (205, 'Schmelzkäsescheiben', 0.40, 'Käse', 'Edeka'),
       (206, 'Schmelzkäsescheiben', 0.40, 'Käse', 'Penny'),
       (207, 'Schmelzkäsescheiben', 0.40, 'Käse', 'Netto'),
       (208, 'Frischkäsefass', 1.90, 'Käse', 'Aldi Süd'),
       (209, 'Frischkäsefass', 1.80, 'Käse', 'Aldi Nord'),
       (210, 'Frischkäsefass', NULL, 'Käse', 'Lidl'),
       (211, 'Frischkäsefass', NULL, 'Käse', 'Rewe'),
       (212, 'Frischkäsefass', NULL, 'Käse', 'Edeka'),
       (213, 'Frischkäsefass', NULL, 'Käse', 'Penny'),
       (214, 'Frischkäsefass', NULL, 'Käse', 'Netto'),
       (215, 'Havarti in Scheiben', 1.25, 'Käse', 'Aldi Süd'),
       (216, 'Havarti in Scheiben', 0.40, 'Käse', 'Aldi Nord'),
       (217, 'Havarti in Scheiben', NULL, 'Käse', 'Lidl'),
       (218, 'Havarti in Scheiben', NULL, 'Käse', 'Rewe'),
       (219, 'Havarti in Scheiben', NULL, 'Käse', 'Edeka'),
       (220, 'Havarti in Scheiben', NULL, 'Käse', 'Penny'),
       (221, 'Havarti in Scheiben', NULL, 'Käse', 'Netto'),
       (222, 'Mozzarella mini', 1.11, 'Käse', 'Aldi Süd'),
       (223, 'Mozzarella mini', 1.06, 'Käse', 'Aldi Nord'),
       (224, 'Mozzarella mini', 0.71, 'Käse', 'Lidl'),
       (225, 'Mozzarella mini', NULL, 'Käse', 'Rewe'),
       (226, 'Mozzarella mini', NULL, 'Käse', 'Edeka'),
       (227, 'Mozzarella mini', 0.84, 'Käse', 'Penny'),
       (228, 'Mozzarella mini', NULL, 'Käse', 'Netto'),
       (229, 'Gouda, mittel am Stück', 4.99, 'Käse', 'Aldi Süd'),
       (230, 'Gouda, mittel am Stück', NULL, 'Käse', 'Aldi Nord'),
       (231, 'Gouda, mittel am Stück', 2.64, 'Käse', 'Lidl'),
       (232, 'Gouda, mittel am Stück', NULL, 'Käse', 'Rewe'),
       (233, 'Gouda, mittel am Stück', NULL, 'Käse', 'Edeka'),
       (234, 'Gouda, mittel am Stück', NULL, 'Käse', 'Penny'),
       (235, 'Gouda, mittel am Stück', NULL, 'Käse', 'Netto'),
       (236, 'Kakaohaltiges Getränkepulver', 3.7, 'Kaffee', 'Aldi Süd'),
       (237, 'Kakaohaltiges Getränkepulver', 2.9, 'Kaffee', 'Aldi Nord'),
       (238, 'Kakaohaltiges Getränkepulver', 2.7, 'Kaffee', 'Lidl'),
       (239, 'Kakaohaltiges Getränkepulver', 2.9, 'Kaffee', 'Rewe'),
       (240, 'Kakaohaltiges Getränkepulver', 2.9, 'Kaffee', 'Edeka'),
       (241, 'Kakaohaltiges Getränkepulver', 2.7, 'Kaffee', 'Penny'),
       (242, 'Kakaohaltiges Getränkepulver', 2.9, 'Kaffee', 'Netto'),
       (243, 'Cappuccino', NULL, 'Kaffee', 'Aldi Süd'),
       (244, 'Cappuccino', 2.74, 'Kaffee', 'Aldi Nord'),
       (245, 'Cappuccino', NULL, 'Kaffee', 'Lidl'),
       (246, 'Cappuccino', NULL, 'Kaffee', 'Rewe'),
       (247, 'Cappuccino', NULL, 'Kaffee', 'Edeka'),
       (248, 'Cappuccino', NULL, 'Kaffee', 'Penny'),
       (249, 'Cappuccino', NULL, 'Kaffee', 'Netto'),
       (250, 'Ceylon-Assam-Tee', NULL, 'Tee', 'Aldi Süd'),
       (251, 'Ceylon-Assam-Tee', 0.75, 'Tee', 'Aldi Nord'),
       (252, 'Ceylon-Assam-Tee', 0.75, 'Tee', 'Lidl'),
       (253, 'Ceylon-Assam-Tee', 0.75, 'Tee', 'Rewe'),
       (254, 'Ceylon-Assam-Tee', 0.75, 'Tee', 'Edeka'),
       (255, 'Ceylon-Assam-Tee', 0.75, 'Tee', 'Penny'),
       (256, 'Ceylon-Assam-Tee', 0.75, 'Tee', 'Netto'),
       (257, 'Waldfrucht', 4.40, 'Tee', 'Aldi Süd'),
       (258, 'Waldfrucht', 2.25, 'Tee', 'Aldi Nord'),
       (259, 'Waldfrucht', 2.40, 'Tee', 'Lidl'),
       (260, 'Waldfrucht', 2.30, 'Tee', 'Rewe'),
       (261, 'Waldfrucht', 3.40, 'Tee', 'Edeka'),
       (262, 'Waldfrucht', NULL, 'Tee', 'Penny'),
       (263, 'Waldfrucht', NULL, 'Tee', 'Netto'),
       (264, 'Fusilli', 2.0, 'Nudeln & Reis', 'Aldi Süd'),
       (265, 'Fusilli', 1.8, 'Nudeln & Reis', 'Aldi Nord'),
       (266, 'Fusilli', 1.9, 'Nudeln & Reis', 'Lidl'),
       (267, 'Fusilli', NULL, 'Nudeln & Reis', 'Rewe'),
       (268, 'Fusilli', 1.6, 'Nudeln & Reis', 'Edeka'),
       (269, 'Fusilli', NULL, 'Nudeln & Reis', 'Penny'),
       (270, 'Fusilli', 1.75, 'Nudeln & Reis', 'Netto'),
       (271, 'Spaghetti', 3.0, 'Nudeln & Reis', 'Aldi Süd'),
       (272, 'Spaghetti', NULL, 'Nudeln & Reis', 'Aldi Nord'),
       (273, 'Spaghetti', 1.0, 'Nudeln & Reis', 'Lidl'),
       (274, 'Spaghetti', 0.8, 'Nudeln & Reis', 'Rewe'),
       (275, 'Spaghetti', 1.2, 'Nudeln & Reis', 'Edeka'),
       (276, 'Spaghetti', 0.9, 'Nudeln & Reis', 'Penny'),
       (277, 'Spaghetti', 1.2, 'Nudeln & Reis', 'Netto'),
       (278, 'Bandnudeln', NULL, 'Nudeln & Reis', 'Aldi Süd'),
       (279, 'Bandnudeln', 2.2, 'Nudeln & Reis', 'Aldi Nord'),
       (280, 'Bandnudeln', 1.4, 'Nudeln & Reis', 'Lidl'),
       (281, 'Bandnudeln', 2.0, 'Nudeln & Reis', 'Rewe'),
       (282, 'Bandnudeln', NULL, 'Nudeln & Reis', 'Edeka'),
       (283, 'Bandnudeln', 1.2, 'Nudeln & Reis', 'Penny'),
       (284, 'Bandnudeln', 2.8, 'Nudeln & Reis', 'Netto'),
       (285, 'Reis Parboiled', 1.5, 'Nudeln & Reis', 'Aldi Süd'),
       (286, 'Reis Parboiled', 1.3, 'Nudeln & Reis', 'Aldi Nord'),
       (287, 'Reis Parboiled', 1.0, 'Nudeln & Reis', 'Lidl'),
       (288, 'Reis Parboiled', 1.0, 'Nudeln & Reis', 'Rewe'),
       (289, 'Reis Parboiled', 1.0, 'Nudeln & Reis', 'Edeka'),
       (290, 'Reis Parboiled', NULL, 'Nudeln & Reis', 'Penny'),
       (291, 'Reis Parboiled', NULL, 'Nudeln & Reis', 'Netto'),
       (292, 'Reis', 0.9, 'Nudeln & Reis', 'Aldi Süd'),
       (293, 'Reis', 0.88, 'Nudeln & Reis', 'Aldi Nord'),
       (294, 'Reis', 1.0, 'Nudeln & Reis', 'Lidl'),
       (295, 'Reis', 1.05, 'Nudeln & Reis', 'Rewe'),
       (296, 'Reis', 0.95, 'Nudeln & Reis', 'Edeka'),
       (297, 'Reis', 0.95, 'Nudeln & Reis', 'Penny'),
       (298, 'Reis', 0.98, 'Nudeln & Reis', 'Netto'),
       (299, 'Milchreis', 1.4, 'Nudeln & Reis', 'Aldi Süd'),
       (300, 'Milchreis', 1.0, 'Nudeln & Reis', 'Aldi Nord'),
       (301, 'Milchreis', NULL, 'Nudeln & Reis', 'Lidl'),
       (302, 'Milchreis', 1.2, 'Nudeln & Reis', 'Rewe'),
       (303, 'Milchreis', NULL, 'Nudeln & Reis', 'Edeka'),
       (304, 'Milchreis', NULL, 'Nudeln & Reis', 'Penny'),
       (305, 'Milchreis', NULL, 'Nudeln & Reis', 'Netto')""")
       
connection.commit()
connection.close()

